# Generated by Django 4.2.13 on 2024-06-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_mailing', 'Может просматривать рассылки'), ('can_add_mailing', 'Может добавлять рассылки')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
