# Generated by Django 5.0.4 on 2024-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('successful', 'успешно'), ('unsuccessful', 'не успешно')], max_length=100, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('once a week', 'один раз в неделю'), ('everyday', 'каждый день'), ('once a month', 'один раз в месяц')], max_length=100, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], max_length=100, verbose_name='статус'),
        ),
    ]
