# Generated by Django 4.2.13 on 2024-06-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Может просматривать рассылки'), ('can_disable_mailing', 'Может отключать рассылки'), ('cannot_edit_mailing', 'Не может редактировать рассылки'), ('cannot_manage_mailing', 'Не может управлять списком рассылок'), ('cannot_change_mailing', 'Не может создавать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('cannot_change_message', 'Не может изменять сообщения')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
